overwrite: true
schema: "schema.json"
documents:
    - "src/graphql/**/*.graphql"
generates:
    src/types/graphql.ts:
        plugins:
            - "typescript"
            - "typed-document-node"
            - "typescript-operations"
            - "fragment-matcher"
